import { useRouter } from 'next/router'
import styles from '../../styles/Home.module.css'
import Link from 'next/link';

export default function Header() {

    const router = useRouter()
    var currentPage = router.pathname
    const linkStyle = {color: '#f50707'}
    
    return (
        <div className={styles.header}>
        <header>
            <title>No Future!</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
            <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
            <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        </header>
        <div>
            <Link href="/" style={(currentPage == '/') ? linkStyle : {}}> NEWS DE LA RUE </Link>
            <Link href="/opinion" style={(currentPage == '/opinion') ? linkStyle : {}}> GUEULANTE DES LECTEURS </Link>
            <Link href="/weather" style={(currentPage == '/weather') ? linkStyle : {}}> MÉTÉO DE NC </Link>
            <Link href="/technology" style={(currentPage == '/technology') ? linkStyle : {}}> TECHNOLOGIES </Link>
            <Link href="/lifestyles" style={(currentPage == '/lifestyles') ? linkStyle : {}}> FASHION </Link>
            <Link href="/business" style={(currentPage == '/business') ? linkStyle : {}}> NEWS DES CORPO-RATS </Link>
            <Link href="/entertainment" style={(currentPage == '/entertainment') ? linkStyle : {}}> S'AMUSER À NC </Link>
            <Link href="/worldnews" style={(currentPage == '/worldnews') ? linkStyle : {}}> LE MONDE SE CASSE LA GUEULE </Link>
        </div>
      </div>
    )
}